SWEngGroup4/scranplan

app/src/main/res/values/colors.xml
Adds the colors file with the current color scheme for the application
=> updates colors to the current color scheme

app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
Set a new android wide default theme.
Will be added to overtime to include elements such as buttons, dialog boxes etc...
=> Created a base theme

app/src/test/java/com/group4sweng/scranplan/UserInfoPrivateTest.java
Updated the User Info Unit Tests
=> update and fix all tests

app/src/androidTest/java/com/group4sweng/scranplan/RecipeInfoFragmentTest.java, app/src/main/java/com/group4sweng/scranplan/RecipeFragment.java, app/src/main/java/com/group4sweng/scranplan/RecipeInfoFragment.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/SearchListFragment.java
The espresso test is done and the test report is finished.
=> C8 favourite recipe new

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/group4sweng/scranplan/APIHandler/APICaller.java, app/src/main/java/com/group4sweng/scranplan/APIHandler/GrocerySearcher.java, app/src/test/java/com/group4sweng/scranplan/APIHandler/APICallerTest.java, app/src/test/java/com/group4sweng/scranplan/APIHandler/GrocerySearcherTest.java
Work on this branch has been suspended due to Tesco shutting its API down, however I will look at other APIs. Wanted to get my work committed to the master so that it doesn't get too far away from the master later when it's restarted.
=> Add API C12 things

app/src/androidTest/java/com/group4sweng/scranplan/HiddenViewsTest.java, app/src/androidTest/java/com/group4sweng/scranplan/RecordedEspressoHelper.java, app/src/main/java/com/group4sweng/scranplan/Helper/HiddenViews.java, app/src/main/java/com/group4sweng/scranplan/ProfileSettings.java
Used for testing shapes module. 
Decided to add documentation + generalize so everyone else can use.
More info here: https://github.com/SWEngGroup4/scranplan/wiki/Custom-test-views
p.s. liking this Github Wiki idea.
=> Added better support for entering custom test screens

app/src/main/java/com/group4sweng/scranplan/Presentation/Presentation.java
fixes first slide showing and updates the dropdown with correct slide
=> fixes first slide showing and updates the dropdown with correct slide

.travis.yml
Adds releases to sentry so bugs can be linked with releases to the master
=> Adds releases to sentry

app/src/main/java/com/group4sweng/scranplan/RecipeFragment.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/HomeRecyclerAdapter.java, app/src/main/res/layout/home_image_recycler.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
Update recipe buttons to include a title and rating
=> Custom image button

app/src/main/java/com/group4sweng/scranplan/MealPlanner/PlannerFragment.java, app/src/main/java/com/group4sweng/scranplan/RecipeFragment.java, app/src/main/res/layout/fragment_planner.xml, app/src/main/res/layout/fragment_recipe.xml
Shouldn't be any issues - literally just adds a button for accessing the shopping list, some dailogue to make it clear the user is added a recipe through the planner when pressing the + button, and made the return button on the planner functional
=> Mealplanner additions

app/src/androidTest/java/com/group4sweng/scranplan/EspressoHelper.java, app/src/androidTest/java/com/group4sweng/scranplan/Helper/HiddenViewsTest.java, app/src/androidTest/java/com/group4sweng/scranplan/Presentation/PresentationTest.java, app/src/androidTest/java/com/group4sweng/scranplan/Presentation/TimerTest.java, app/src/androidTest/java/com/group4sweng/scranplan/ProfileSettingsTest.java, app/src/androidTest/java/com/group4sweng/scranplan/ProfileTest.java, app/src/androidTest/java/com/group4sweng/scranplan/PublicProfileTest.java, app/src/androidTest/java/com/group4sweng/scranplan/SoundHandler/AudioTest.java, app/src/main/java/com/group4sweng/scranplan/Presentation/Presentation.java, app/src/main/java/com/group4sweng/scranplan/Presentation/PresentationTimer.java, build.gradle
Fixed bug in timer where it would display on the first slide.
Added new UI tests for continuity, and fixed issue where timer was counting down instead of up and for values greater than 60 seconds was displaying in-correctly.
Also added a super helpful navigation thingy into EspressoHelper. 
Code in EspressoHelper:
```
public static void navigateToRecipe(String recipeName) throws InterruptedException {
onView(withId(R.id.menuSortButton))
.perform(click());
onView(withId(R.id.nameCheckBox))
.check(matches(isNotChecked()))
.perform(click());
onView(withText("OK"))
.perform(click());
onView(withId(R.id.menuSearch))
.perform(click());
onView(isAssignableFrom(SearchView.class))
.perform(typeSearchViewText(recipeName))
.perform(pressKey(KeyEvent.KEYCODE_ENTER));
Thread.sleep(SEARCH_WAIT_TIME); …
```
=> Timer UI tests and fixes. (Also includes helpful new recipe navigation tool for tests)

app/src/androidTest/java/com/group4sweng/scranplan/Credentials.java, app/src/androidTest/java/com/group4sweng/scranplan/Helper/HiddenViewsTest.java, app/src/androidTest/java/com/group4sweng/scranplan/HomeTest.java, app/src/androidTest/java/com/group4sweng/scranplan/LoginTest.java, app/src/androidTest/java/com/group4sweng/scranplan/MealPlanner/PlannerFragmentTest.java, app/src/androidTest/java/com/group4sweng/scranplan/MealPlanner/PlannerInfoFragmentTest.java, app/src/androidTest/java/com/group4sweng/scranplan/MealPlanner/PortionsTest.java, app/src/androidTest/java/com/group4sweng/scranplan/Presentation/PresentationTest.java, app/src/androidTest/java/com/group4sweng/scranplan/Presentation/TimerTest.java, app/src/androidTest/java/com/group4sweng/scranplan/ProfileSettingsTest.java, app/src/androidTest/java/com/group4sweng/scranplan/PublicProfileTest.java, app/src/androidTest/java/com/group4sweng/scranplan/RecipeInfo/RecipeInfoFragmentTest.java, app/src/androidTest/java/com/group4sweng/scranplan/SideMenuTest.java, app/src/androidTest/java/com/group4sweng/scranplan/SoundHandler/AudioTest.java
Fixing various tests and updating tests so they work.
=> Test Fixing

app/build.gradle, app/src/androidTest/java/com/group4sweng/scranplan/MealPlanner/PlannerFragmentTest.java, app/src/androidTest/java/com/group4sweng/scranplan/MealPlanner/PlannerInfoFragmentTest.java, app/src/main/java/com/group4sweng/scranplan/MealPlanner/PlannerFragment.java, app/src/main/java/com/group4sweng/scranplan/MealPlanner/PlannerListFragment.java, app/src/main/java/com/group4sweng/scranplan/RecipeInfo/RecipeInfoFragment.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/SearchListFragment.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/SearchQuery.java
Fixes issues with meal planner searching closing #81, tests are: PlannerFragmentTest and PlannerInfoFragmentTest
=> Fix meal planner search

app/src/main/java/com/group4sweng/scranplan/Home.java, app/src/main/java/com/group4sweng/scranplan/MealPlanner/PlannerFragment.java, app/src/main/java/com/group4sweng/scranplan/RecipeFragment.java
=> Meal planner pref fix

app/build.gradle, app/src/androidTest/java/com/group4sweng/scranplan/Adverts/AdViewHolderTest.java, app/src/main/AndroidManifest.xml, app/src/main/java/com/group4sweng/scranplan/Adverts/AdViewHolder.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/HomeQueries.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/HomeRecyclerAdapter.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/RecipeFragment.java, app/src/main/res/layout/ad_unified.xml, app/src/main/res/layout/advert_express_ad_container.xml, app/src/main/res/values/strings.xml
Adds adverts, can be removed and changed as required. This user story was to add the functionality of native adverts to the application. This is all delivered through AdMob.
=> C19 Gold Membership Adverts

app/src/androidTest/java/com/group4sweng/scranplan/HomeTest.java, app/src/main/AndroidManifest.xml, app/src/main/java/com/group4sweng/scranplan/Home.java, app/src/main/java/com/group4sweng/scranplan/Login.java, app/src/main/java/com/group4sweng/scranplan/PublicProfile.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/SearchListFragment.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/SearchQuery.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/SearchRecyclerAdapter.java
=> User searching

app/src/main/AndroidManifest.xml, app/src/main/java/com/group4sweng/scranplan/Home.java, app/src/main/java/com/group4sweng/scranplan/MealPlanner/PlannerFragment.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/RecipeFragment.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/SearchQuery.java, app/src/main/java/com/group4sweng/scranplan/Social/FeedFragment.java
Fixes the two searching bugs :) - fix #113 and fix #108
=> Fix #113 and #108

app/src/main/AndroidManifest.xml, app/src/main/java/com/group4sweng/scranplan/RecipeInfo/RecipeInfoFragment.java, app/src/main/java/com/group4sweng/scranplan/RecipeInfo/RecipeReviewFragment.java, app/src/main/java/com/group4sweng/scranplan/RecipeInfo/recipeReviewRecyclerAdapter.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/RecipeFragment.java, app/src/main/java/com/group4sweng/scranplan/Social/FeedFragment.java, app/src/main/java/com/group4sweng/scranplan/Social/FeedRecyclerAdapter.java, app/src/main/java/com/group4sweng/scranplan/Social/PostPage.java, app/src/main/java/com/group4sweng/scranplan/Social/ProfilePosts.java, app/src/main/res/layout/fragment_recipe_info.xml
Fixed deleting review problem
Altered info screen layout, Title shouldn't impact the buttons at the top
Fixed review duplication problem and image upload problem
=> Jp bug fixing

app/src/main/java/com/group4sweng/scranplan/PublicProfile.java
Fixed weird fragment transaction bug #126 replacement commit
=> Fragment Transaction bug

app/src/main/java/com/group4sweng/scranplan/Helper/RecipeHelpers.java, app/src/main/java/com/group4sweng/scranplan/ShoppingList.java, app/src/main/res/layout/activity_shoppinglist.xml
Design issues and slight bug picked up
=> Design all fixed

app/src/main/java/com/group4sweng/scranplan/SearchFunctions/RecipeFragment.java
because I've not seen this first hand it will catch the exception and fix #117
=> catch illegalstateexception

.travis.yml, app/src/main/AndroidManifest.xml, app/src/main/java/com/group4sweng/scranplan/Home.java, app/src/main/java/com/group4sweng/scranplan/MainActivity.java, app/src/main/java/com/group4sweng/scranplan/ProfileSettings.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/RecipeFragment.java, app/src/main/java/com/group4sweng/scranplan/SideMenu.java, app/src/main/java/com/group4sweng/scranplan/UserInfo/UserInfoPrivate.java
Fixed:
- Scrollviews for recipes not updating after filters are changed within the profile.
- Search options not being retained when moving between activites.
(Used shared preferences Android storage approach, much easier than using Firebase for this type of approach.)
=> Fixed Search options and Scrollviews not updating

app/src/main/java/com/group4sweng/scranplan/Social/FeedRecyclerAdapter.java
=> fix for 133

app/src/main/java/com/group4sweng/scranplan/RecipeInfo/RecipeReviewFragment.java
think this fixes #120 (not fully convinced though) and fixes #128
=> Fix reviews

app/src/main/java/com/group4sweng/scranplan/Home.java, app/src/main/java/com/group4sweng/scranplan/SearchFunctions/HomeQueries.java
getSharedPreferences no longer used - not sure if these were ever working? loadSearchOptions() is now never called and storeSearchOptions() & resetFilters() seem to only be used in tests?
=> changes onResume in home - shared preferences was now working

app/src/main/java/com/group4sweng/scranplan/Home.java, app/src/main/java/com/group4sweng/scranplan/ProfileSettings.java
Fixes:
- Filter Search Options not getting updated when a user changes there filter settings in the profile settings page.
- Filter Search Options not getting reset when a user logs out, registers a new user and logs back in.
=> Shared preferences fix for Search Options

app/src/main/java/com/group4sweng/scranplan/Presentation/Presentation.java, app/src/main/java/com/group4sweng/scranplan/Presentation/PresentationSlide.java, app/src/main/java/com/group4sweng/scranplan/Presentation/Views/PresentationTextView.java, app/src/main/java/com/group4sweng/scranplan/RecipeCreation/RecipeSteps.java, app/src/main/java/com/group4sweng/scranplan/RecipeCreation/RecipeStepsRecycler.java, app/src/main/java/com/group4sweng/scranplan/SoundHandler/AudioURL.java, app/src/main/java/com/group4sweng/scranplan/SoundHandler/StockSounds.java, app/src/main/java/com/group4sweng/scranplan/Xml/XmlParser.java, app/src/main/java/com/group4sweng/scranplan/Xml/XmlSerializar.java, app/src/main/res/layout/recipe_step_recycler.xml
Added:
- Audio for slides that load once the slide loads. (Audio now meets the spec required :0)
- Options for allowing your audio to loop on a slide
- Options for selecting in seconds when the audio starts
Fixed:
- Audio not stopping when existing a presentation
- Timer audio not working. Timers still have audio included but I significantly simplified so audio for timers is not read in through XML anymore and is just using stock sounds for the ticking and ding sounds for when it finishes. 
I've tested different inputs, various different audio file types and sizes. apologies if it breaks any tests and I know I haven't submitted a test report but it's nearly 5am ish so i might pass the baton for that one.
=> Audio for individual slides
